apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogs:
        datasourceUid: ""
      serviceMap:
        datasourceUid: "prometheus"

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus
    jsonData:
      timeInterval: "15s"
